image:
  - Visual Studio 2019

install:
  - set QTDIR=C:\Qt\5.14.0\msvc2017\bin
  - curl -LO https://slproweb.com/download/Win32OpenSSL-1_1_1d.exe
  - powershell ".\\Win32OpenSSL-1_1_1d.exe /silent /sp- /suppressmsgboxes /DIR='C:\\Libraries\\OpenSSL-Win32'"
  - git clone https://github.com/TheWanderingCoel/ZBar.git C:\Libraries\ZBar
  - git clone https://github.com/TheWanderingCoel/QREncode.git C:\Libraries\QREncode
  - set PATH=%QTDIR%;%PATH%;
  - git submodule update --init

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x86

build_script:
  - mkdir build && cd build
  - qmake ../
  - nmake
  - windeployqt trojan-qt5.exe
  - del *.o *.h *.cpp *.stash *.qrc *.obj Makefile
  - rd /s /q bearer iconengines translations bearer styles platforms imageformats
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libiconv-2.dll
  - curl -LO https://github.com/TheWanderingCoel/Trojan-Qt5-DLL/raw/master/libzbar-0.dll
  - 7z a Trojan-Qt5-Windows.zip *
  - cd ..

artifacts:
- path: build\Trojan-Qt5-Windows.zip
  name: Trojan-Qt5

deploy:
  provider: GitHub
  description: "Trojan-Qt5 Release"
  auth_token:
    secure: uAMRAuhJjhHbPRvsKDUGYBDrrDPhlj2q1zHICgjSo7K2CSmVMxHreSMJYqer4y2k
  artifact: Trojan-Qt5
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
